### PR TITLE
Added callback option for invocations

### PR DESCRIPTION
**Pull request by lhotamir**
I have added option for a callback when sending an invocation to the hub. I believe it is the feature requested in #23

### CODE REVIEW

**Comment by mandrewcito** [comment]
Thank you, i will accept your PR but first i will make some tests for the new feature!

**Comment by lhotamir** [comment]
I can try to add some tests myself tomorrow, I need to resolve the conflicts anyway

**Comment by lhotamir** [comment]
I have resolved the conflict and added a new test, feel free to add more if you have some in mind

**Comment by mandrewcito** [comment]
Wow, so cool, thank you!

**Pull request merged**
